---
name: CI
on: [push, pull_request]

# Write permissions needed for Test report
# (may be fixed by https://github.com/dorny/test-reporter/pull/174)
permissions:
  statuses: write
  checks: write

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        compiler:
          - gcc-9
          - gcc-10
          - gcc-11
          - clang-12
          - clang-13
          - clang-14

    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt install -y cmake ninja-build
          sudo apt install -y doxygen graphviz

      - name: Install compiler (Linux)
        if: ${{ startsWith(matrix.os,'ubuntu-') }}
        run: |
          sudo apt install -y ${{ matrix.compiler }}

      - name: Install libgcrypt
        if: ${{ startsWith(matrix.os,'ubuntu-') }}
        run: sudo apt install -y libgcrypt20-dev

      - name: Configure
        run: |
          export SHELL=$(which sh)
          export CXX=$(echo ${{ matrix.compiler }} | sed -E 's/^(g|clang)(cc)?/\1++/')
          cmake -G Ninja -S . -B build

      - name: Build
        working-directory: build
        run: ninja srecord-executables-version

      - name: Test
        working-directory: build
        run: |
          ninja test_arglex_ambiguous test_crc16 test_fletcher16 test_hyphen test_url_decode
          ctest --output-junit ctest.junit.xml

  docs:
    name: Documentation
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt install -y cmake ninja-build
          sudo apt install -y doxygen graphviz
          sudo apt install -y groff psutils ghostscript

      - name: Configure
        run: cmake -G Ninja -S . -B build

      - name: man pages
        working-directory: build
        run: ninja man

      - name: Doxygen
        working-directory: build
        run: ninja doxygen

      - name: PDF
        working-directory: build
        run: ninja doco

      - name: Web Site
        working-directory: build
        run: ninja man-html web-site
